--     use {
--         'fatih/vim-go',
--         run = ':GoUpdateBinaries',
--         ft = 'go',
--         setup = function()
--             vim.g.go_diagnostics_enabled = 1
--             vim.g.go_highlight_fields = 1
--             vim.g.go_highlight_functions = 1
--             vim.g.go_highlight_function_calls = 1
--             vim.g.go_highlight_extra_types = 1
--             vim.g.go_highlight_operators = 1
--             vim.g.go_fmt_autosave = 1
--             vim.g.go_fmt_command = "goimports"
--             vim.g.go_auto_type_info = 1
--             local t = function(str)
--                 return vim.api.nvim_replace_termcodes(str, true, true, true)
--             end
--
--             local check_back_space = function()
--                 local col = vim.fn.col('.') - 1
--                 if col == 0 or vim.fn.getline('.'):sub(col, col):match('%s') then
--                     return true
--                 else
--                     return false
--                 end
--             end
--
--             _G.tab_complete = function()
--                 if vim.fn.pumvisible() == 1 then
--                     return t "<C-n>"
--                 elseif check_back_space() then
--                     return t "<Tab>"
--                 else
--                     return t "<C-x><C-o>"
--                 end
--             end
--
--             _G.s_tab_complete = function()
--                 if vim.fn.pumvisible() == 1 then
--                     return t "<C-p>"
--                 else
--                     return t "<C-h>"
--                 end
--             end
--
--             _G.enter_key = function()
--                 if vim.fn.pumvisible() == 1 then
--                     return t "<C-y>"
--                 else
--                     return t "<CR>"
--                 end
--             end
--
--             vim.api.nvim_set_keymap("i", "<tab>", "<C-R>=v:lua.tab_complete()<CR>" ,{silent = true, noremap = true})
--             vim.api.nvim_set_keymap("i", "<s-tab>", "<C-R>=v:lua.s_tab_complete()<CR>" ,{silent = true, noremap = true})
--             vim.api.nvim_set_keymap('i', '<enter>', '<C-R>=v:lua.enter_key()<CR>' ,{silent = true, noremap = true})
--         end
--     }
-- require('fatih').setup(config) 
